def menuchuong1():
    print("|============================================|")
    print("|   ~~~~~  CHƯƠNG 1: PYTHON CƠ BẢN  ~~~~~    |")
    print("|============================================|")
    print("|  1. Đổi °C sang °F                         |")
    print("|  2. Các lệnh có cấu trúc                   |")
    print("|  3. Hàm số                                 |")
    print("|  4. Kiểu dữ liệu danh sách (list)          |")
    print("|  5. Kiểu dữ liệu xâu kí tự (string)        |")
    print("|  6. Kiểu dữu liệu tập hợp (set)            |")
    print("|  7. Kiểu dữ liệu từ điển (dictionary)      |")
    print("|  8. Module và Package                      |")
    print("|  9. Đọc và ghi tệp                         |")
    print("| 10. Ngoại lệ và xử lý ngoại lệ             |")
    print("| 11. Lập trình hướng đối tượng              |")
    print("|  0.  THOÁT  <--|                           |")
    print("|============================================|")
def menubai2():
    print("|=====================================================|")
    print("|      ~~~~~  BÀI 2: CÁC LỆNH CÓ CẤU TRÚC  ~~~~~      |")
    print("|=====================================================|")
    print("| 1. Viết chương trình nhập một số tự nhiên n         |")
    print("|(n  [50, 150]) và tính các giá trị sau:            |")
    print("|\ta) Tính tổng và in ra các số nguyên tố nhỏ hơn n. |")
    print("|\tb) Tính tổng của tất cả các ước số của n.         |")
    print("|\tc) Tính tổng các số chẵn từ 1 đến n bằng hai cách:|")
    print("|  sử dụng vòng lặp for và vòng lặp while.            |")
    print("| 0. THOÁT  <--|                                      |")
    print("|=====================================================|")
def menubai3():
    print("|=====================================================|")
    print("|             ~~~~~  BÀI 3: HÀM SỐ  ~~~~~             |")
    print("|=====================================================|")
    print("| 1. Viết chương trình nhập một số tự nhiên n         |")
    print("| (n  [50, 150]) và các hàm sau:                    |")
    print("|\ta) Hàm trả lại số các ước số thực sự của n.       |")
    print("|\tb) Hàm trả lại 1 nếu n là nguyên tố, ngược lại    |")
    print("|  hàm trả về 0.                                      |")
    print("|\tc) Hàm đếm số các ước số là lẻ của n.             |")
    print("|\td) Hàm đếm số các số nguyên tố nhỏ hơn n.         |")
    print("|\te) Hàm tính tổng tất cả các ước số thực sự của n. |")
    print("| 0. THOÁT  <--|                                      |")
    print("|=====================================================|")
def menubai5():
    print("|======================================================|")
    print("|     ~~~~~  BÀI 5: KIỂU DỮ LIỆU XÂU KÍ TỰ  ~~~~~      |")
    print("|======================================================|")
    print("| 1. Kiểm tra xem xâu Str2 có nằm trong Str1 hay không?|")
    print("| 2. Đếm số lần xuất hiện của Str2 trong Str1          |")
    print("| 3. Chèn chuỗi St2 vào vị trí k trong Str1            |")
    print("| 0. THOÁT  <--|                                       |")
    print("|======================================================|")

def menubai6():
    print("|======================================================|")
    print("|      ~~~~~  BÀI 6: KIỂU DỮ LIỆU TẬP HỢP  ~~~~~       |")
    print("|======================================================|")
    print("| 1. Tạo tập hợp A                                     |")
    print("| 2. Tạo tập hợp B từ tập hợp A                        |")
    print("| 3. Tạo tập hợp C từ tập hợp B                        |")
    print("| 0. THOÁT  <--|                                       |")
    print("|======================================================|")

def menubai7():
    print("|======================================================|")
    print("|      ~~~~~  BÀI 7: KIỂU DỮ LIỆU TỪ ĐIỂN  ~~~~~       |")
    print("|======================================================|")
    print("| 1. In điểm lớn nhất                                  |")
    print("| 2. In môn và điểm có điểm lớn nhất                   |")
    print("| 3. In các điểm số chẵn                               |")
    print("| 4. Tính trung bình các điểm                          |")
    print("| 5. Tạo từ điển mới với các môn lớn hơn 7 điểm        |")
    print("| 6. Đảo ngược từ điển                                 |")
    print("| 0. THOÁT  <--|                                       |")
    print("|======================================================|")

def menubai8():
    print("|======================================================|")
    print("|       ~~~~~  BÀI 8: MODULE VÀ PACKAGE  ~~~~~         |")
    print("|======================================================|")
    print("| 1. Tính tổng hai số                                  |")
    print("| 2. Tính tích hai số                                  |")
    print("| 3. Tính lũy thừa                                     |")
    print("| 4. Tính căn bậc 2                                    |")
    print("| 5. Tính hàm tan                                      |")
    print("| 6. Giải phương trình bậc 2                           |")
    print("| 0. THOÁT  <--|                                       |")
    print("|======================================================|")

def menubai9():
    print("|======================================================|")
    print("|        ~~~~~  BÀI 9: ĐỌC VÀ GHI TỆP  ~~~~~           |")
    print("|======================================================|")
    print("| 1. Đọc dữ liệu từ tệp fin.txt và tính tổng các dãy số|")
    print("| 2. Xuất kết quả ra tệp fout.txt                      |")
    print("| 0. THOÁT  <--|                                       |")
    print("|======================================================|")


def menubai10():
    print("|======================================================|")
    print("|   ~~~~~  BÀI 10: NGOẠI LỆ VÀ XỬ LÝ NGOẠI LỆ  ~~~~~   |")
    print("|======================================================|")
    print("| 1. Tính giá trị phân số a/b                          |")
    print("| 0. THOÁT  <--|                                       |")
    print("|======================================================|")

def menubai11():
    print("|======================================================|")
    print("|   ~~~~~  BÀI 11: LẬP TRÌNH HƯỚNG ĐỐI TƯỢNG  ~~~~~    |")
    print("|======================================================|")
    print("| 1. Nhập danh sách nhân viên                          |")
    print("| 2. Sắp xếp theo tuổi giảm dần và in ra danh sách     |")
    print("| 3. Ghi danh sách nhân viên vào file NhanVien.txt     |")
    print("| 4. Đọc và in danh sách nhân viên từ file NhanVien.txt|")
    print("| 0. THOÁT  <--|                                       |")
    print("|======================================================|")


def menuchuong2():
    print("|============================================|")
    print("|~~~~~ CHƯƠNG 2: LẬP TRÌNH VỚI THƯ VIỆN ~~~~~|")
    print("|============================================|")
    print("| 1. Thư viện NumPy                          |")
    print("| 2. Thư viện MatplotLib                     |")
    print("| 3. Thư viện SymPy                          |")
    print("| 0.  THOÁT  <--|                            |")
    print("|============================================|")


def menubai12():
    print("|===================================================|")
    print("|           ~~~~~    TẠO MA TRẬN    ~~~~~           |")
    print("|===================================================|")
    print("| 1. Tạo vectơ x và ma trận A, B, C                 |")
    print("| 2. Tính tích của vectơ x và ma trận A             |")
    print("| 3. Tính tích của hai ma trận A và B               |")
    print("| 4. Tính tích của ma trận chuyển vị C và ma trận B |")
    print("| 0.  THOÁT  <--|                                   |")
    print("|===================================================|")
def menubai15():
    print("------ Viết hàm giải hệ phương trình ------")
    print("1. Viết hàm giải hệ phương trình {2x – 5y + z = −5, 4x + 2y – 2z = 2, x + y − z = 0}")
    print("2. Viết hàm tính giới hạn của hàm f = (x3- 3x2)1/3 + (x2- 2x)1/2 khi x tiến tới 5")
    print("3. Viết hàm tính đạo hàm của hàm f = (2x - 1)/(x + 2)")
    print("4. Viết hàm tính nguyên hàm của hàm f = x/(x2 + 1)")
    print("5. Viết hàm tính tích phân của hàm f = (1 - xtan(x))/(x2cos(x) + x) Với x  [0, 2pi/3]")
    print("0. Thoát")
    print("-------------------------------------")


