# Generated by Django 4.2.6 on 2023-10-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_phong_delete_producty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenPhong',
            fields=[
                ('maChuyenPhong', models.AutoField(primary_key=True, serialize=False)),
                ('ngayChuyen', models.DateField()),
                ('tienChuyenPhong', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('maDichVu', models.AutoField(primary_key=True, serialize=False)),
                ('tenDichVu', models.CharField(max_length=255)),
                ('moTa', models.TextField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('maKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('hoVaTenDem', models.CharField(max_length=255)),
                ('soDienThoai', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('cccd', models.CharField(max_length=255)),
                ('diaChi', models.TextField()),
                ('taiKhoan', models.CharField(max_length=255)),
                ('matKhau', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('maNhanVien', models.AutoField(primary_key=True, serialize=False)),
                ('hoVaTenDem', models.CharField(max_length=255)),
                ('chucVu', models.CharField(max_length=255)),
                ('luong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taiKhoan', models.CharField(max_length=255)),
                ('matKhau', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('danhSachChuyenPhong', models.ManyToManyField(related_name='nhanvien_chuyenphong', to='myapp.chuyenphong')),
            ],
        ),
        migrations.CreateModel(
            name='ThueDichVu',
            fields=[
                ('maThueDichVu', models.AutoField(primary_key=True, serialize=False)),
                ('soLuong', models.PositiveIntegerField()),
                ('thanhTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dichVu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuedichvu_dichvu', to='myapp.dichvu')),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuedichvu_nhanvien', to='myapp.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ThuePhong',
            fields=[
                ('maThuePhong', models.AutoField(primary_key=True, serialize=False)),
                ('ngayNhanPhong', models.DateField()),
                ('ngayTraPhong', models.DateField()),
                ('tongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trangThai', models.CharField(max_length=255)),
                ('tienDatCoc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('danhSachThueDichVu', models.ManyToManyField(related_name='thuephong_thuedichvu', to='myapp.thuedichvu')),
                ('khachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuephong_khachhang', to='myapp.khachhang')),
                ('nhanVien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thuephong_nhanvien', to='myapp.nhanvien')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuephong_phong', to='myapp.phong')),
            ],
        ),
        migrations.CreateModel(
            name='TraPhong',
            fields=[
                ('maTraPhong', models.AutoField(primary_key=True, serialize=False)),
                ('ngayTraPhong', models.DateField()),
                ('tongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nhanVien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trapphong_nhanvien', to='myapp.nhanvien')),
                ('thuePhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trapphong_thuephong', to='myapp.thuephong')),
            ],
        ),
        migrations.AddField(
            model_name='thuedichvu',
            name='thuePhong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuedichvu_thuephong', to='myapp.thuephong'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='danhSachThueDichVu',
            field=models.ManyToManyField(related_name='nhanvien_thuedichvu', to='myapp.thuedichvu'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='danhSachThuePhong',
            field=models.ManyToManyField(related_name='nhanvien_thuephong', to='myapp.thuephong'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='danhSachTraPhong',
            field=models.ManyToManyField(related_name='nhanvien_trapphong', to='myapp.traphong'),
        ),
        migrations.CreateModel(
            name='NhanPhong',
            fields=[
                ('maNhanPhong', models.AutoField(primary_key=True, serialize=False)),
                ('ngayNhanPhong', models.DateField()),
                ('thuePhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhanphong_thuephong', to='myapp.thuephong')),
            ],
        ),
        migrations.AddField(
            model_name='khachhang',
            name='danhSachThuePhong',
            field=models.ManyToManyField(related_name='khachhang_thuephong', to='myapp.thuephong'),
        ),
        migrations.AddField(
            model_name='dichvu',
            name='danhSachThueDichVu',
            field=models.ManyToManyField(related_name='dichvu_thuedichvu', to='myapp.thuedichvu'),
        ),
        migrations.AddField(
            model_name='chuyenphong',
            name='khachHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyenphong_khachhang', to='myapp.khachhang'),
        ),
        migrations.AddField(
            model_name='chuyenphong',
            name='phongCu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyenphong_phongcu', to='myapp.phong'),
        ),
        migrations.AddField(
            model_name='chuyenphong',
            name='phongMoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyenphong_phongmoi', to='myapp.phong'),
        ),
        migrations.AddField(
            model_name='phong',
            name='danhSachChuyenPhong',
            field=models.ManyToManyField(related_name='phong_chuyenphong', to='myapp.chuyenphong'),
        ),
        migrations.AddField(
            model_name='phong',
            name='danhSachThuePhong',
            field=models.ManyToManyField(related_name='phong_thuephong', to='myapp.thuephong'),
        ),
    ]
