# Generated by Django 4.2.6 on 2023-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_chuyenphong_ngaychuyen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
