# Generated by Django 4.2.6 on 2023-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_nhanvien_is_active_nhanvien_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='matKhau',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='taiKhoan',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
