# Generated by Django 4.2.6 on 2023-11-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_dichvu_image_dichvu_trangthai_khachhang_trangthai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuephong',
            name='hinhThucThanhToan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thuephong',
            name='trangThaiThanhToan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
