# Generated by Django 4.2.6 on 2023-11-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_thuephong_hinhthucthanhtoan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tang',
            fields=[
                ('maTang', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='phong',
            name='tang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phongs', to='myapp.tang'),
        ),
    ]
