# Generated by Django 4.2.6 on 2023-11-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_tang_phong_tang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='tang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phongs', to='myapp.tang'),
        ),
    ]
