# Generated by Django 4.2.6 on 2023-11-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_phong_tang'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuephong',
            name='gioNhanPhong',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='thuephong',
            name='gioTraPhong',
            field=models.TimeField(default='00:00'),
        ),
    ]
